services:
  otel-collector:
    container_name: otel-collector-test-same-tags
    image: otel/opentelemetry-collector-contrib:0.104.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otelcol/config.yaml:/etc/otelcol/config.yaml:ro
    env_file:
      - ../.env
    ports:
      - "4317:4317"
      - "4318:4318"

  service-a:
    container_name: service-a-test-same-tags
    build: ./app
    depends_on:
      - otel-collector

  service-b:
    container_name: service-b-test-same-tags
    build: ./app
    depends_on:
      - otel-collector

  service-c:
    container_name: service-c-test-same-tags
    build: ./app
    depends_on:
      - otel-collector
